version: '3'

services:
  cassandra:
    image: cassandra:4.0.6
    ports:
      - "9042:9042"
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
    restart: always
  presto:
    image: ahanaio/prestodb-sandbox
    ports:
      - "8080:8080"
